extends: airbnb-base
plugins:
  - "no-only-tests"
env:
  node: true
  mocha: true
overrides:
  - files:
      - "**/*.js"
    rules:
      max-len:
        - error
        - code: 200
      consistent-return: off
      func-names: off
      no-param-reassign: off
      no-underscore-dangle: off
      no-plusplus: off
  - files:
      - "**/*.js"
    rules:
      func-names: off
      no-console:
        - error
  - files:
      - "services/**/api/fittings/*.js"
    rules:
      camelcase: off
  - files:
      - "tests/**/*.js"
      - "smoke/tests/*.js"
      - "db-migration.js"
    rules:
      "import/no-extraneous-dependencies":
        - error
        - devDependencies: true
      prefer-arrow-callback: off
  - files:
      - "tests/**/*.js"
    rules:
      no-only-tests/no-only-tests:
        - error

