swagger: "2.0"
info:
  version: "2.0.0"
  title: Poker Stats
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /swagger:
    x-swagger-pipe: swagger_raw

  /api/v2/groups:
    x-swagger-router-controller: groups
    get:
      operationId: getGroups
      responses:
        200:
          description: GetGroupsResponseDefinition
          schema:
            $ref: "#/definitions/GetGroupsResponseDefinition"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: createGroup
      parameters:
        - name: body
          in: body
          description: The new group details
          required: true
          schema:
            $ref: "#/definitions/CreateGroupRequestDefinition"
      responses:
        201:
          description: createGroupResponseDefinition
          schema:
            $ref: "#/definitions/GroupDefinition"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /api/v2/groups/{groupId}/players:
    x-swagger-router-controller: players
    parameters:
      - $ref: '#/parameters/GroupId'
    get:
      operationId: getPlayers
      responses:
        200:
          description: GetPlayersResponseDefinition
          schema:
            $ref: "#/definitions/GetPlayersResponseDefinition"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: createPlayer
      parameters:
        - name: body
          in: body
          description: The new group details
          required: true
          schema:
            $ref: "#/definitions/CreatePlayerRequestDefinition"
      responses:
        201:
          description: createGroupResponseDefinition
          schema:
            $ref: "#/definitions/PlayerDefinition"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /api/v2/groups/{groupId}/players/{playerId}:
    x-swagger-router-controller: players
    parameters:
      - $ref: '#/parameters/GroupId'
      - $ref: '#/parameters/PlayerId'
    get:
      operationId: getPlayer
      responses:
        200:
          description: PlayerDefinition
          schema:
            $ref: "#/definitions/PlayerDefinition"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  ErrorResponse:
    required:
      - title
    properties:
      title:
        type: string
      detail:
        type: string
  GroupDefinition:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      createdAt:
        type: string
  PlayerDefinition:
    type: object
    properties:
      id:
        type: string
      groupId:
        type: string
      firstName:
        type: string
      familyName:
        type: string
      phone:
        type: string
      email:
        type: string
      imageUrl:
        type: string
      birthday:
        type: string
      createdAt:
        type: string
  GetGroupsResponseDefinition:
    type: object
    properties:
      metadata:
        type: object
        properties:
          count:
            type: integer
      groups:
        type: array
        items:
          $ref: "#/definitions/GroupDefinition"
  GetPlayersResponseDefinition:
    type: object
    properties:
      metadata:
        type: object
        properties:
          count:
            type: integer
      players:
        type: array
        items:
          $ref: "#/definitions/PlayerDefinition"
  CreateGroupRequestDefinition:
    type: object
    required:
      - name
    properties:
      name:
        type: string
  CreatePlayerRequestDefinition:
    type: object
    required:
      - firstName
      - familyName
    properties:
      firstName:
        type: string
      familyName:
        type: string
      phone:
        type: string
      email:
        type: string
      imageUrl:
        type: string
      birthday:
        type: string

parameters:
  GroupId:
    name: groupId
    in: path
    description: The id of the group (uuid)
    required: true
    type: string
    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
  PlayerId:
    name: playerId
    in: path
    description: The id of the player (uuid)
    required: true
    type: string
    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
